#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Charger.Resource", IsApplication=true)]

namespace Charger
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public const int btnAdvance = 2130968578;
			
			// aapt resource value: 0x7f04000d
			public const int btnConector = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int btnLeft = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int btnRegress = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int btnRight = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int btnStop = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int lbConeccion = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int lbErrores = 2130968590;
			
			// aapt resource value: 0x7f040000
			public const int linearLayout1 = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int linearLayout2 = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int linearLayout3 = 2130968587;
			
			// aapt resource value: 0x7f040001
			public const int space = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int space2 = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int space3 = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int space4 = 2130968586;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
